Updated poseidon builders tests
webb-tools/anon pull request #110
Opened 2021-03-04 15:24 UTC by filiplazovic

2021-03-05 15:02 UTC, filiplazovic commented
Noticed some comments are missing after some rebase in the past, gotta fix it here

2021-03-08 10:23 UTC, shekohex requested changes
Sounds Good!
Just a few changes, I made it as a suggestion so you can do it quickly from here!

2021-03-08 10:23 UTC, shekohex commented on pallets/merkle/src/lib.rs
> +	pub fn add_leaf(tree: &mut GroupTree, data: ScalarData, zero_tee: &Vec<[u8; 32]>, h: &Poseidon) {
```suggestion
	pub fn add_leaf(tree: &mut GroupTree, data: ScalarData, zero_tree: &Vec<[u8; 32]>, h: &Poseidon) {
```

2021-03-08 10:23 UTC, shekohex commented on pallets/merkle/src/lib.rs
> +				let zero_h = Scalar::from_bytes_mod_order(zero_tee[i]);
```suggestion
				let zero_h = Scalar::from_bytes_mod_order(zero_tree[i]);
```

2021-03-08 10:23 UTC, shekohex commented on pallets/merkle/src/traits.rs
> +	/// Check if nullifier is already used, in which case throws an error
```suggestion
	/// Check if nullifier is already used, in which case return an error
```

2021-03-08 11:02 UTC, shekohex approved these changes

2021-03-08 11:06 UTC, merged