Bulletproofs Update - Storing generators in runtime storage
webb-tools/anon pull request #154
Opened 2021-06-13 22:50 UTC by drewstone

2021-06-13 23:09 UTC, drewstone commented
We should also consider getting this work into the `develop` branch once we agree whether this should be merged.

2021-06-14 19:13 UTC, nepoche requested changes

2021-06-14 21:23 UTC, drewstone commented on pallets/merkle/src/lib.rs
> +			vkey_required: bool,
Removed now. Thanks for the note.

2021-06-15 13:31 UTC, shekohex approved these changes

2021-06-15 13:39 UTC, merged